apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 3.x
    helm:
      values: |
        singleBinary:
          persistence:
            enabled: true
            size: 50Gi
            accessModes:
            - ReadWriteOnce
        loki:
          auth_enabled: false
          limits_config.reject_old_samples_max_age: 24h
          commonConfig:
            replication_factor: 1
          storage:
            type: 'filesystem'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true